ALTER TABLE products ADD COLUMN min_stock DECIMAL(10,2) DEFAULT 0;
ALTER TABLE products ADD COLUMN max_stock DECIMAL(10,2) DEFAULT 0;
ALTER TABLE products ADD COLUMN multiple_qty DECIMAL(10,2) DEFAULT 1;
